version: '3.7'

services:

  db:
    image: postgres:13.5-alpine
    environment:
      # Create db
      POSTGRES_DB: users
      # Use postgres/secret user/password credentials
      POSTGRES_PASSWORD: secret
      # enforce UTC timezone
      TZ: UTC
    volumes:
      - postgres-users-data-local:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer:4
    ports:
      - 8081:8080

# permanent storage of data.
# > docker volume rm postgres_users-data-local
volumes:
  postgres-users-data-local:
